name: learn-github-actions

on: [workflow_dispatch]

jobs:
  just-ls-command:
    runs-on: self-hosted

    steps:
      - name: Print message
        run: echo "Hello from GitHub Runner"

      - name: List files
        run: ls -l

      - name: Show hostname
        run: hostname